"""Create the MD Parking camera dashboard once."""
from __future__ import annotations

import asyncio

from homeassistant.components import frontend
from homeassistant.components.lovelace import LOVELACE_DATA, MODE_STORAGE
from homeassistant.components.lovelace import dashboard as lovelace_dashboard
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er

from .const import DOMAIN

DASHBOARD_PATH = "md-parking"


def _dashboard_config(camera_ids: list[str], button_ids: list[str]) -> dict:
    cards = []
    if button_ids:
        cards.append(
            {
                "type": "horizontal-stack",
                "cards": [
                    {
                        "type": "button",
                        "entity": entity_id,
                        "icon": "mdi:gate-open",
                        "show_state": False,
                        "tap_action": {
                            "action": "call-service",
                            "service": "button.press",
                            "service_data": {"entity_id": entity_id},
                            "confirmation": {"text": "Открыть этот шлагбаум?"},
                        },
                        "hold_action": {"action": "none"},
                    }
                    for entity_id in button_ids
                ],
            }
        )
    cards.extend(
        {
            "type": "picture-entity",
            "entity": entity_id,
            "camera_view": "live",
            "show_name": True,
            "show_state": True,
        }
        for entity_id in camera_ids
    )
    return {
        "views": [
            {
                "title": "MD Parking",
                "path": "cameras",
                "icon": "mdi:cctv",
                "cards": cards,
            }
        ]
    }


async def async_ensure_dashboard(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Create a sidebar dashboard without overwriting an existing one."""
    await asyncio.sleep(2)
    registry = er.async_get(hass)
    camera_ids = sorted(
        item.entity_id
        for item in registry.entities.values()
        if item.config_entry_id == entry.entry_id and item.domain == "camera"
    )
    button_ids = sorted(
        item.entity_id
        for item in registry.entities.values()
        if item.config_entry_id == entry.entry_id and item.domain == "button"
    )
    if not camera_ids or LOVELACE_DATA not in hass.data:
        return

    collection = lovelace_dashboard.DashboardsCollection(hass)
    await collection.async_load()
    existing = next(
        (item for item in collection.async_items() if item.get("url_path") == DASHBOARD_PATH),
        None,
    )
    if existing:
        config = hass.data[LOVELACE_DATA].dashboards.get(DASHBOARD_PATH)
        if config is not None:
            current = await config.async_load(False)
            # Migrate only the exact camera-only layout generated by v0.2.8;
            # never overwrite a dashboard the user has edited.
            if current == _dashboard_config(camera_ids, []):
                await config.async_save(_dashboard_config(camera_ids, button_ids))
            else:
                # v0.3.0 used the newer perform-action spelling, which is not
                # executed by some HA frontend releases. Migrate only those
                # generated button actions and preserve every other card.
                changed = False
                for stack in current.get("views", [{}])[0].get("cards", []):
                    if stack.get("type") != "horizontal-stack":
                        continue
                    for card in stack.get("cards", []):
                        action = card.get("tap_action", {})
                        entity_id = card.get("entity")
                        if (
                            action.get("action") == "perform-action"
                            and action.get("perform_action") == "button.press"
                            and isinstance(entity_id, str)
                        ):
                            card["tap_action"] = {
                                "action": "call-service",
                                "service": "button.press",
                                "service_data": {"entity_id": entity_id},
                                "confirmation": {"text": "Открыть этот шлагбаум?"},
                            }
                            changed = True
                if changed:
                    await config.async_save(current)
        return

    item = await collection.async_create_item(
        {
            "url_path": DASHBOARD_PATH,
            "title": "MD Parking",
            "icon": "mdi:gate",
            "show_in_sidebar": True,
            "require_admin": False,
        }
    )
    config = lovelace_dashboard.LovelaceStorage(hass, item)
    await config.async_save(_dashboard_config(camera_ids, button_ids))
    hass.data[LOVELACE_DATA].dashboards[DASHBOARD_PATH] = config
    frontend.async_register_built_in_panel(
        hass,
        "lovelace",
        sidebar_title="MD Parking",
        sidebar_icon="mdi:gate",
        frontend_url_path=DASHBOARD_PATH,
        config={"mode": MODE_STORAGE},
        require_admin=False,
        show_in_sidebar=True,
    )
